### ISSUE TITLE
Unexpected unit test failure when building zucchini

### ISSUE THREAD

**Issue by trentontrees** [Comcast/zucchini#23]
<code>-------------------------------------------------------
##  T E S T S

Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@1997c457
[DEBUG-ThreadIdx[0]] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[ThreadIdx[0]] starting
[DEBUG-ThreadIdx[1]] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[ThreadIdx[1]] starting
[DEBUG-ThreadIdx[2]] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[ThreadIdx[2]] starting
[DEBUG-ThreadIdx[4]] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[ThreadIdx[4]] starting
[DEBUG-ThreadIdx[3]] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[ThreadIdx[3]] starting
[DEBUG-ThreadIdx[2]] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for BarrierTest
[DEBUG-ThreadIdx[2]] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for BarrierTest
[DEBUG-ThreadIdx[3]] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for BarrierTest
[DEBUG-ThreadIdx[3]] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for BarrierTest
[DEBUG-ThreadIdx[0]] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for BarrierTest
[DEBUG-ThreadIdx[0]] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for BarrierTest
[DEBUG-ThreadIdx[1]] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for BarrierTest
[DEBUG-ThreadIdx[1]] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for BarrierTest
[DEBUG-ThreadIdx[4]] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for BarrierTest
[DEBUG-ThreadIdx[4]] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for BarrierTest
[DEBUG-ThreadIdx[4]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Entering barrier on ThreadIdx[4]
[DEBUG-ThreadIdx[3]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Entering barrier on ThreadIdx[3]
[DEBUG-ThreadIdx[1]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Entering barrier on ThreadIdx[1]
[DEBUG-ThreadIdx[0]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Entering barrier on ThreadIdx[0]
[DEBUG-ThreadIdx[2]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Entering barrier on ThreadIdx[2]
[DEBUG-ThreadIdx[1]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Leaving barrier on ThreadIdx[1]
[DEBUG-ThreadIdx[4]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Leaving barrier on ThreadIdx[4]
[DEBUG-ThreadIdx[0]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Leaving barrier on ThreadIdx[0]
[DEBUG-ThreadIdx[2]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Leaving barrier on ThreadIdx[2]
[DEBUG-ThreadIdx[3]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Leaving barrier on ThreadIdx[3]
[DEBUG-ThreadIdx[1]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Entering barrier on ThreadIdx[1]
[DEBUG-ThreadIdx[2]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Entering barrier on ThreadIdx[2]
[DEBUG-ThreadIdx[3]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Entering barrier on ThreadIdx[3]
[DEBUG-ThreadIdx[4]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Entering barrier on ThreadIdx[4]
[DEBUG-ThreadIdx[0]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: Entering barrier on ThreadIdx[0]
[DEBUG-ThreadIdx[4]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: BarrierCount for [ThreadIdx[4]] is 5, and numContexts is 5 after sync
[DEBUG-ThreadIdx[2]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: BarrierCount for [ThreadIdx[2]] is 5, and numContexts is 5 after sync
[DEBUG-ThreadIdx[1]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: BarrierCount for [ThreadIdx[1]] is 5, and numContexts is 5 after sync
[DEBUG-ThreadIdx[0]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: BarrierCount for [ThreadIdx[0]] is 5, and numContexts is 5 after sync
[DEBUG-ThreadIdx[3]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: BarrierCount for [ThreadIdx[3]] is 5, and numContexts is 5 after sync
[DEBUG-ThreadIdx[2]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: BarrierCount for [ThreadIdx[2]] is 5, and numContexts is 5 after sync
[DEBUG-ThreadIdx[3]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: BarrierCount for [ThreadIdx[3]] is 5, and numContexts is 5 after sync
[DEBUG-ThreadIdx[4]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: BarrierCount for [ThreadIdx[4]] is 5, and numContexts is 5 after sync
[DEBUG-ThreadIdx[0]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: BarrierCount for [ThreadIdx[0]] is 5, and numContexts is 5 after sync
[DEBUG-ThreadIdx[1]] com.comcast.zucchini.glue.ZucchiniBarrierGlue: BarrierCount for [ThreadIdx[1]] is 5, and numContexts is 5 after sync

Failed scenarios:
zucchini-ib.feature:29 # Scenario: Verify that barriers enforce serial execution after failure

6 Scenarios (1 failed, 5 passed)
18 Steps (1 failed, 17 passed)
0m0.354s

java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at org.testng.Assert.fail(Assert.java:94)
    at com.comcast.zucchini.glue.ZucchiniBarrierGlue.barrier_serial_end(ZucchiniBarrierGlue.java:158)
    at ✽.Then Our barriers executed in order(zucchini-ib.feature:32)

Failed scenarios:
zucchini-ib.feature:29 # Scenario: Verify that barriers enforce serial execution after failure

6 Scenarios (1 failed, 5 passed)
18 Steps (1 failed, 17 passed)
0m0.348s

java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at org.testng.Assert.fail(Assert.java:94)
    at com.comcast.zucchini.glue.ZucchiniBarrierGlue.barrier_serial_end(ZucchiniBarrierGlue.java:158)
    at ✽.Then Our barriers executed in order(zucchini-ib.feature:32)

Failed scenarios:
zucchini-ib.feature:29 # Scenario: Verify that barriers enforce serial execution after failure

6 Scenarios (1 failed, 5 passed)
18 Steps (1 failed, 17 passed)
0m0.348s

java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at org.testng.Assert.fail(Assert.java:94)
    at com.comcast.zucchini.glue.ZucchiniBarrierGlue.barrier_serial_end(ZucchiniBarrierGlue.java:158)
    at ✽.Then Our barriers executed in order(zucchini-ib.feature:32)

Failed scenarios:
zucchini-ib.feature:29 # Scenario: Verify that barriers enforce serial execution after failure

6 Scenarios (1 failed, 5 passed)
18 Steps (1 failed, [ERROR-ThreadIdx[2]] com.comcast.zucchini.AbstractZucchiniTest: ERROR running test: {}
cucumber.runtime.CucumberException: java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at com.comcast.zucchini.TestNGZucchiniRunner.runCukes(TestNGZucchiniRunner.java:79) ~[classes/:na]
    at com.comcast.zucchini.AbstractZucchiniTest.runWith(AbstractZucchiniTest.java:218) ~[classes/:na]
    at com.comcast.zucchini.TestRunner.run(TestRunner.java:51) [classes/:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at org.testng.Assert.fail(Assert.java:94) ~[testng-6.8.8.jar:na]
    at com.comcast.zucchini.glue.ZucchiniBarrierGlue.barrier_serial_end(ZucchiniBarrierGlue.java:158) ~[test-classes/:na]
    at ✽.Then Our barriers executed in order(zucchini-ib.feature:32) ~[na:na]
17 passed)
0m[ERROR-ThreadIdx[3]] com.comcast.zucchini.AbstractZucchiniTest: ERROR running test: {}
cucumber.runtime.CucumberException: java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at com.comcast.zucchini.TestNGZucchiniRunner.runCukes(TestNGZucchiniRunner.java:79) ~[classes/:na]
    at com.comcast.zucchini.AbstractZucchiniTest.runWith(AbstractZucchiniTest.java:218) ~[classes/:na]
    at com.comcast.zucchini.TestRunner.run(TestRunner.java:51) [classes/:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at org.testng.Assert.fail(Assert.java:94) ~[testng-6.8.8.jar:na]
    at com.comcast.zucchini.glue.ZucchiniBarrierGlue.barrier_serial_end(ZucchiniBarrierGlue.java:158) ~[test-classes/:na]
    at ✽.Then Our barriers executed in order(zucchini-ib.feature:32) ~[na:na]
[DEBUG-ThreadIdx[3]] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[ThreadIdx[3]] finished
0.346s

java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at org.testng.Assert.fail(Assert.java:94)
    at com.comcast.zucchini.glue.ZucchiniBarrierGlue.barrier_serial_end(ZucchiniBarrierGlue.java:158)
    at ✽.Then Our barriers executed in order(zucchini-ib.feature:32)

[DEBUG-ThreadIdx[2]] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[ThreadIdx[2]] finished
[ERROR-ThreadIdx[4]] com.comcast.zucchini.AbstractZucchiniTest: ERROR running test: {}
cucumber.runtime.CucumberException: java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at com.comcast.zucchini.TestNGZucchiniRunner.runCukes(TestNGZucchiniRunner.java:79) ~[classes/:na]
    at com.comcast.zucchini.AbstractZucchiniTest.runWith(AbstractZucchiniTest.java:218) ~[classes/:na]
    at com.comcast.zucchini.TestRunner.run(TestRunner.java:51) [classes/:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at org.testng.Assert.fail(Assert.java:94) ~[testng-6.8.8.jar:na]
    at com.comcast.zucchini.glue.ZucchiniBarrierGlue.barrier_serial_end(ZucchiniBarrierGlue.java:158) ~[test-classes/:na]
    at ✽.Then Our barriers executed in order(zucchini-ib.feature:32) ~[na:na]
[DEBUG-ThreadIdx[4]] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[ThreadIdx[4]] finished

Failed scenarios:
zucchini-ib.feature:29 # Scenario: Verify that barriers enforce serial execution after failure

6 Scenarios (1 failed, 5 passed)
18 Steps (1 failed, 17 passed)
0m0.346s

java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at org.testng.Assert.fail(Assert.java:94)
    at com.comcast.zucchini.glue.ZucchiniBarrierGlue.barrier_serial_end(ZucchiniBarrierGlue.java:158)
    at ✽.Then Our barriers executed in order(zucchini-ib.feature:32)

[ERROR-ThreadIdx[0]] com.comcast.zucchini.AbstractZucchiniTest: ERROR running test: {}
cucumber.runtime.CucumberException: java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at com.comcast.zucchini.TestNGZucchiniRunner.runCukes(TestNGZucchiniRunner.java:79) ~[classes/:na]
    at com.comcast.zucchini.AbstractZucchiniTest.runWith(AbstractZucchiniTest.java:218) ~[classes/:na]
    at com.comcast.zucchini.TestRunner.run(TestRunner.java:51) [classes/:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at org.testng.Assert.fail(Assert.java:94) ~[testng-6.8.8.jar:na]
    at com.comcast.zucchini.glue.ZucchiniBarrierGlue.barrier_serial_end(ZucchiniBarrierGlue.java:158) ~[test-classes/:na]
    at ✽.Then Our barriers executed in order(zucchini-ib.feature:32) ~[na:na]
[DEBUG-ThreadIdx[0]] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[ThreadIdx[0]] finished
[ERROR-ThreadIdx[1]] com.comcast.zucchini.AbstractZucchiniTest: ERROR running test: {}
cucumber.runtime.CucumberException: java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at com.comcast.zucchini.TestNGZucchiniRunner.runCukes(TestNGZucchiniRunner.java:79) ~[classes/:na]
    at com.comcast.zucchini.AbstractZucchiniTest.runWith(AbstractZucchiniTest.java:218) ~[classes/:na]
    at com.comcast.zucchini.TestRunner.run(TestRunner.java:51) [classes/:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.AssertionError: The internal barrierCount[1] was not set to zero.
    at org.testng.Assert.fail(Assert.java:94) ~[testng-6.8.8.jar:na]
    at com.comcast.zucchini.glue.ZucchiniBarrierGlue.barrier_serial_end(ZucchiniBarrierGlue.java:158) ~[test-classes/:na]
    at ✽.Then Our barriers executed in order(zucchini-ib.feature:32) ~[na:na]
[DEBUG-ThreadIdx[1]] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[ThreadIdx[1]] finished
[DEBUG-ThreadIdx[4]] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for BarrierTest
[DEBUG-ThreadIdx[2]] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for BarrierTest
[DEBUG-ThreadIdx[1]] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for BarrierTest
[DEBUG-ThreadIdx[0]] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for BarrierTest
[DEBUG-ThreadIdx[3]] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for BarrierTest
[DEBUG-potato] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[potato] starting
[DEBUG-eggplant] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[eggplant] starting
[DEBUG-tomato] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[tomato] starting
[DEBUG-potato] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for MultipleZucchiniCukesTest
[DEBUG-eggplant] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for MultipleZucchiniCukesTest
[DEBUG-potato] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for MultipleZucchiniCukesTest
[DEBUG-eggplant] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for MultipleZucchiniCukesTest
[DEBUG-tomato] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for MultipleZucchiniCukesTest
[DEBUG-tomato] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for MultipleZucchiniCukesTest

1 Scenarios (1 passed)
3 Steps (3 passed)
0m0.003s

[DEBUG-eggplant] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[eggplant] finished

1 Scenarios (1 passed[DEBUG-eggplant] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for MultipleZucchiniCukesTest
)
3 Steps (3 passed)
0m0.003s

[DEBUG-potato] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[potato] finished
[DEBUG-potato] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for MultipleZucchiniCukesTest

1 Scenarios (1 passed)
3 Steps (3 passed)
0m0.003s

[DEBUG-tomato] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[tomato] finished
[DEBUG-tomato] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for MultipleZucchiniCukesTest
[DEBUG-asparagus] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[asparagus] starting
[DEBUG-carrots] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[carrots] starting
[DEBUG-cabbages] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[cabbages] starting
[DEBUG-onions] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[onions] starting
[DEBUG-celery] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[celery] starting
[DEBUG-turnips] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[turnips] starting
[DEBUG-carrots] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for ParallelZucchiniCukesTest
[DEBUG-carrots] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for ParallelZucchiniCukesTest
[DEBUG-celery] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for ParallelZucchiniCukesTest
[DEBUG-celery] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for ParallelZucchiniCukesTest
[DEBUG-turnips] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for ParallelZucchiniCukesTest
[DEBUG-cabbages] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for ParallelZucchiniCukesTest
[DEBUG-turnips] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for ParallelZucchiniCukesTest
[DEBUG-cabbages] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for ParallelZucchiniCukesTest
[DEBUG-onions] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for ParallelZucchiniCukesTest
[DEBUG-onions] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for ParallelZucchiniCukesTest
[DEBUG-asparagus] com.comcast.zucchini.AbstractZucchiniTest: Setup method was not implemented for ParallelZucchiniCukesTest
[DEBUG-asparagus] com.comcast.zucchini.AbstractZucchiniTest: Setup formatter method was not implemented for ParallelZucchiniCukesTest

3 Scenarios (3 passed)
9 Steps (9 passed)
0m0.005s

[DEBUG-cabbages] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[cabbages] finished
[DEBUG-cabbages] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for ParallelZucchiniCukesTest

3 Scenarios (3 passed)
9 Steps (9 passed)
0m0.006s

[DEBUG-turnips] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[turnips] finished

3 Scenarios (3 passed)
9 Steps (9 passed)
0m0.014s

[DEBUG-asparagus] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[asparagus] finished
[DEBUG-turnips] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for ParallelZucchiniCukesTest
[DEBUG-asparagus] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for ParallelZucchiniCukesTest

3 Scenarios (3 passed)
9 Steps (9 passed)
0m0.016s

[DEBUG-carrots] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[carrots] finished
[DEBUG-carrots] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for ParallelZucchiniCukesTest

3 Scenarios (3 passed)
9 Steps (9 passed)
0m0.005s

[DEBUG-onions] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[onions] finished
[DEBUG-onions] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for ParallelZucchiniCukesTest

3 Scenarios (3 passed)
9 Steps (9 passed)
0m0.013s

[DEBUG-celery] com.comcast.zucchini.AbstractZucchiniTest: ZucchiniTest[celery] finished
[DEBUG-celery] com.comcast.zucchini.AbstractZucchiniTest: Cleanup method was not implemented for ParallelZucchiniCukesTest
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.842 sec <<< FAILURE!
run(com.comcast.zucchini.BarrierTest)  Time elapsed: 0.97 sec  <<< FAILURE!
java.lang.AssertionError: There were 5 failed executions against a TestContext expected [0] but found [5]
    at org.testng.Assert.fail(Assert.java:94)
    at org.testng.Assert.failNotEquals(Assert.java:494)
    at org.testng.Assert.assertEquals(Assert.java:123)
    at org.testng.Assert.assertEquals(Assert.java:370)
    at com.comcast.zucchini.AbstractZucchiniTest.runParallel(AbstractZucchiniTest.java:173)
    at com.comcast.zucchini.AbstractZucchiniTest.run(AbstractZucchiniTest.java:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
    at org.testng.SuiteRunner.run(SuiteRunner.java:254)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

[ERROR-Thread-0] com.comcast.zucchini.ZucchiniShutdownHook: FATAL ERROR: BUILD FAILED - Check Report For Details

Results :

Failed tests:   run(com.comcast.zucchini.BarrierTest): There were 5 failed executions against a TestContext expected [0] but found [5]

Tests run: 3, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.893 s
[INFO] Finished at: 2015-09-30T10:22:46-07:00
[INFO] Final Memory: 19M/363M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project zucchini: Error occurred in starting fork, check output in log -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException</code>

**Comment by andrewbenton** [comment]
What are your run settings?

**Comment by trentontrees** [comment]
Fixed in Commit c1513183ec67390e1b1852914130cf1f385b2ca3.

It was occurring during a <code>mvn clean test</code>
